-- Option B (H2): history-only mortgage entries (T1; contract v5 3a3d033, T3-cleared with conditions 1–5).
-- GENERATED by supabase/tests/mortgage_history/generate_migration.py from this template; edit the template, not the output.
--
-- A history entry is a real past payment or escrow item that a loan's confirmed opening (statement) balance already
-- includes. It lives in its own table, so no build older than this release reads it (no extra deduction), and it never
-- changes any mortgage_details column, balance effect or review cause — when recorded, voided, or in any rollback.
-- Duplicate protection (rule 5) spans the normal tables, the history tables and same-property unlinked older entries,
-- under the loan lock, from all four insert paths.

-- ---------------------------------------------------------------------------------------------------------------
-- 1. History tables (RLS and grants mirror mortgage_payments; append-only: no DELETE grant, no-delete trigger).
-- ---------------------------------------------------------------------------------------------------------------
create table mortgage_history_payments (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references accounts(id) on delete cascade,
  property_id uuid not null references properties(id) on delete cascade,
  mortgage_id uuid not null references mortgage_details(id),
  payment_date date not null,
  amount numeric(10, 2) not null check (amount > 0),
  principal_amount numeric(10, 2) not null check (principal_amount >= 0),
  interest_amount numeric(10, 2) not null check (interest_amount >= 0),
  -- the statement date this entry was declared as already included in (taken from the loan, never from the client)
  declared_as_of date not null,
  duplicate_ack_matches integer check (duplicate_ack_matches > 0),
  voided boolean not null default false,
  voided_at timestamptz,
  void_reason text,
  created_at timestamptz not null default now(),
  constraint mortgage_history_payments_split_matches_amount check (abs(amount - (principal_amount + interest_amount)) < 0.01)
);
create index mortgage_history_payments_loan_idx on mortgage_history_payments (mortgage_id, payment_date);
create index mortgage_history_payments_account_date_idx on mortgage_history_payments (account_id, payment_date);

create table mortgage_history_escrow (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references accounts(id) on delete cascade,
  property_id uuid not null references properties(id) on delete cascade,
  mortgage_id uuid not null references mortgage_details(id),
  transaction_date date not null,
  transaction_type text not null check (transaction_type in ('deposit', 'disbursement')),
  amount numeric(10, 2) not null check (amount > 0),
  description text,
  declared_as_of date not null,
  duplicate_ack_matches integer check (duplicate_ack_matches > 0),
  voided boolean not null default false,
  voided_at timestamptz,
  void_reason text,
  created_at timestamptz not null default now()
);
create index mortgage_history_escrow_loan_idx on mortgage_history_escrow (mortgage_id, transaction_date);

alter table mortgage_history_payments enable row level security;
alter table mortgage_history_escrow enable row level security;
create policy "members can manage their mortgage history payments"
  on mortgage_history_payments for all
  using (is_account_member(account_id))
  with check (is_account_member(account_id));
create policy "members can manage their mortgage history escrow"
  on mortgage_history_escrow for all
  using (is_account_member(account_id))
  with check (is_account_member(account_id));
revoke all on mortgage_history_payments, mortgage_history_escrow from anon;
revoke delete, truncate on mortgage_history_payments, mortgage_history_escrow from authenticated;

-- Override count on the normal tables too (a normal entry can match a history entry).
alter table mortgage_payments add column duplicate_ack_matches integer check (duplicate_ack_matches > 0);
alter table mortgage_escrow_transactions add column duplicate_ack_matches integer check (duplicate_ack_matches > 0);

-- ---------------------------------------------------------------------------------------------------------------
-- 2. Duplicate rule (contract rule 5). PRIVATE (T3 condition 1): no direct execution by anon/authenticated. Called only
--    from the four insert triggers, each of which has already verified the inserting account's membership, locked the
--    property's active loan FOR UPDATE and checked that the loan belongs to that account; it counts only for that
--    loan / property / account. The lock serialises concurrent inserts into any of the tables for the same loan.
-- ---------------------------------------------------------------------------------------------------------------
create or replace function mortgage_enforce_duplicate_rule(
  p_kind text, p_account uuid, p_property uuid, p_mortgage uuid, p_date date, p_amount numeric, p_type text, p_ack integer
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  n_loan int;
  n_history int;
  n_unlinked int;
  total int;
  counts text;
begin
  if p_kind = 'payment' then
    -- payments match on date + TOTAL amount (not the principal/interest split; contract rule 5)
    select count(*) into n_loan from public.mortgage_payments
     where mortgage_id = p_mortgage and account_id = p_account and not voided and payment_date = p_date and amount = p_amount;
    select count(*) into n_history from public.mortgage_history_payments
     where mortgage_id = p_mortgage and account_id = p_account and not voided and payment_date = p_date and amount = p_amount;
    select count(*) into n_unlinked from public.mortgage_payments
     where mortgage_id is null and property_id = p_property and account_id = p_account and not voided
       and payment_date = p_date and amount = p_amount;
  elsif p_kind = 'escrow' then
    select count(*) into n_loan from public.mortgage_escrow_transactions
     where mortgage_id = p_mortgage and account_id = p_account and not voided and transaction_date = p_date
       and amount = p_amount and transaction_type = p_type;
    select count(*) into n_history from public.mortgage_history_escrow
     where mortgage_id = p_mortgage and account_id = p_account and not voided and transaction_date = p_date
       and amount = p_amount and transaction_type = p_type;
    select count(*) into n_unlinked from public.mortgage_escrow_transactions
     where mortgage_id is null and property_id = p_property and account_id = p_account and not voided
       and transaction_date = p_date and amount = p_amount and transaction_type = p_type;
  else
    raise exception 'Unknown mortgage entry kind %.', p_kind using errcode = '22023';
  end if;
  total := n_loan + n_history + n_unlinked;
  counts := json_build_object('loan', n_loan, 'history', n_history, 'unlinked', n_unlinked, 'total', total)::text;

  if total = 0 then
    if p_ack is not null then
      raise exception 'The matching entry is no longer active, so this isn''t a duplicate now. Nothing was saved; save again to record it normally.'
        using errcode = 'ZM5MB', detail = counts;
    end if;
    return;
  end if;
  if p_ack is null then
    -- Worded for older pages too (they can't confirm; contract rule 7 / T3 condition 5).
    raise exception 'An identical entry already exists for % (% on this loan, % in its opening-balance history, % earlier not linked to a loan). Nothing was saved. If this is a separate payment, reload the page and record it again; the updated page lets you confirm it.',
      p_date, n_loan, n_history, n_unlinked
      using errcode = 'ZM5MA', detail = counts;
  end if;
  if p_ack <> total then
    raise exception 'The number of identical entries for % changed to % while you were confirming. Nothing was saved; check them and confirm again.',
      p_date, total
      using errcode = 'ZM5MA', detail = counts;
  end if;
end;
$$;
revoke all on function mortgage_enforce_duplicate_rule(text, uuid, uuid, uuid, date, numeric, text, integer) from public, anon, authenticated;

-- ---------------------------------------------------------------------------------------------------------------
-- 3. Normal insert functions: identical to 20261004100000 except the one duplicate-rule call (T3 condition 3). The
--    triggers created by 20261004100000 keep pointing at these functions; grants are unchanged (still revoked).
-- ---------------------------------------------------------------------------------------------------------------
create or replace function mortgage_payment_apply_locked()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  l public.mortgage_details%rowtype;
begin
  if auth.uid() is not null and not public.is_account_member(new.account_id) then
    raise exception 'Not a member of this workspace.' using errcode = '42501';
  end if;
  select * into l from public.mortgage_details where property_id = new.property_id and not voided for update;
  if not found then
    raise exception 'No active mortgage_details found for property %; enter loan terms before logging payments.', new.property_id;
  end if;
  if l.account_id <> new.account_id then
    raise exception 'This mortgage belongs to a different workspace.' using errcode = '42501';
  end if;
  if new.mortgage_id is not null and new.mortgage_id <> l.id then
    raise exception 'A new payment can only be recorded against the property''s active mortgage.' using errcode = 'ZM5M1';
  end if;
  perform public.mortgage_enforce_duplicate_rule('payment', new.account_id, new.property_id, l.id, new.payment_date, new.amount, null, new.duplicate_ack_matches);
  if new.principal_amount > l.current_balance then
    raise exception 'Principal amount (%) exceeds the current mortgage balance (%).', new.principal_amount, l.current_balance;
  end if;

  new.mortgage_id := l.id;
  new.voided := false;
  new.voided_at := null;
  new.void_reason := null;
  new.void_outcome := null;

  update public.mortgage_details
     set current_balance = l.current_balance - new.principal_amount,
         principal_version = l.principal_version + 1,
         updated_at = now()
   where id = l.id;
  insert into public.mortgage_balance_effects
    (account_id, property_id, mortgage_id, source_kind, source_id, effect, principal_delta, principal_epoch, escrow_epoch)
  values (new.account_id, new.property_id, l.id, 'payment', new.id, 'applied', -new.principal_amount, l.principal_epoch, l.escrow_epoch);

  if public.mortgage_entry_may_be_covered(new.payment_date, l.principal_as_of, l.principal_figure_at) then
    insert into public.mortgage_balance_review_causes
      (account_id, property_id, review_mortgage_id, balance_kind, cause, source_kind, source_id, context)
    values (new.account_id, new.property_id, l.id, 'principal', 'possibly_covered_by_statement', 'payment', new.id,
            public.mortgage_cause_context('payment', to_jsonb(new), l));
  end if;
  return new;
end;
$$;
create or replace function mortgage_escrow_apply_locked()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  l public.mortgage_details%rowtype;
  before_escrow numeric(12, 2);
  delta numeric(12, 2);
begin
  if auth.uid() is not null and not public.is_account_member(new.account_id) then
    raise exception 'Not a member of this workspace.' using errcode = '42501';
  end if;
  select * into l from public.mortgage_details where property_id = new.property_id and not voided for update;
  if not found then
    raise exception 'No active mortgage_details found for property %; enter loan terms before logging escrow transactions.', new.property_id;
  end if;
  if l.account_id <> new.account_id then
    raise exception 'This mortgage belongs to a different workspace.' using errcode = '42501';
  end if;
  if new.mortgage_id is not null and new.mortgage_id <> l.id then
    raise exception 'A new escrow entry can only be recorded against the property''s active mortgage.' using errcode = 'ZM5M1';
  end if;
  perform public.mortgage_enforce_duplicate_rule('escrow', new.account_id, new.property_id, l.id, new.transaction_date, new.amount, new.transaction_type, new.duplicate_ack_matches);
  before_escrow := coalesce(l.escrow_balance, 0);
  if new.transaction_type = 'disbursement' and new.amount > before_escrow then
    raise exception 'Disbursement amount (%) exceeds the current escrow balance (%).', new.amount, before_escrow;
  end if;
  delta := case when new.transaction_type = 'deposit' then new.amount else -new.amount end;

  new.mortgage_id := l.id;
  new.voided := false;
  new.voided_at := null;
  new.void_reason := null;
  new.void_outcome := null;

  update public.mortgage_details
     set escrow_balance = before_escrow + delta,
         escrow_version = l.escrow_version + 1,
         updated_at = now()
   where id = l.id;
  insert into public.mortgage_balance_effects
    (account_id, property_id, mortgage_id, source_kind, source_id, effect, escrow_delta, principal_epoch, escrow_epoch)
  values (new.account_id, new.property_id, l.id, 'escrow', new.id, 'applied', delta, l.principal_epoch, l.escrow_epoch);

  if public.mortgage_entry_may_be_covered(new.transaction_date, l.escrow_as_of, l.escrow_figure_at) then
    insert into public.mortgage_balance_review_causes
      (account_id, property_id, review_mortgage_id, balance_kind, cause, source_kind, source_id, context)
    values (new.account_id, new.property_id, l.id, 'escrow', 'possibly_covered_by_statement', 'escrow', new.id,
            public.mortgage_cause_context('escrow', to_jsonb(new), l));
  end if;
  return new;
end;
$$;

-- The override count is part of a normal entry's immutable facts (separate small guard; the integrity activity guard
-- is not modified).
create or replace function mortgage_ack_immutable()
returns trigger
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if new.duplicate_ack_matches is distinct from old.duplicate_ack_matches then
    raise exception 'A recorded mortgage entry can''t be changed. Void it and record a new entry instead.' using errcode = 'ZM5M2';
  end if;
  return new;
end;
$$;
revoke all on function mortgage_ack_immutable() from public, anon, authenticated;
create trigger mortgage_payments_ack_immutable before update on mortgage_payments
  for each row execute function mortgage_ack_immutable();
create trigger mortgage_escrow_transactions_ack_immutable before update on mortgage_escrow_transactions
  for each row execute function mortgage_ack_immutable();

-- ---------------------------------------------------------------------------------------------------------------
-- 4. History inserts: eligibility under the loan lock (contract rule 1), duplicate rule, no balance effect.
-- ---------------------------------------------------------------------------------------------------------------
create or replace function mortgage_history_insert_locked()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  l public.mortgage_details%rowtype;
  is_payment boolean := tg_table_name = 'mortgage_history_payments';
  entry_date date;
  as_of date;
begin
  if auth.uid() is not null and not public.is_account_member(new.account_id) then
    raise exception 'Not a member of this workspace.' using errcode = '42501';
  end if;
  select * into l from public.mortgage_details where property_id = new.property_id and not voided for update;
  if not found then
    raise exception 'History entries need the property''s active loan; this property has none.' using errcode = 'ZM5MC';
  end if;
  if l.account_id <> new.account_id then
    raise exception 'This mortgage belongs to a different workspace.' using errcode = '42501';
  end if;
  if new.mortgage_id is not null and new.mortgage_id <> l.id then
    raise exception 'History can only be recorded for the property''s active loan (history for an earlier or inactive loan isn''t supported).'
      using errcode = 'ZM5MC';
  end if;
  if is_payment then
    entry_date := (to_jsonb(new)->>'payment_date')::date;
    as_of := l.principal_as_of;
  else
    entry_date := (to_jsonb(new)->>'transaction_date')::date;
    as_of := l.escrow_as_of;
  end if;
  if as_of is null then
    raise exception 'Set the statement date for this balance first (the date your opening balance is from). History entries are only for dates on or before it.'
      using errcode = 'ZM5MC';
  end if;
  if entry_date > as_of then
    raise exception 'This entry is dated after your statement date (%), so it changes the balance. Record it as a normal entry.', as_of
      using errcode = 'ZM5MC';
  end if;

  if is_payment then
    perform public.mortgage_enforce_duplicate_rule('payment', new.account_id, new.property_id, l.id, entry_date,
      (to_jsonb(new)->>'amount')::numeric, null, (to_jsonb(new)->>'duplicate_ack_matches')::integer);
  else
    perform public.mortgage_enforce_duplicate_rule('escrow', new.account_id, new.property_id, l.id, entry_date,
      (to_jsonb(new)->>'amount')::numeric, to_jsonb(new)->>'transaction_type', (to_jsonb(new)->>'duplicate_ack_matches')::integer);
  end if;

  new.mortgage_id := l.id;
  new.declared_as_of := as_of;
  new.voided := false;
  new.voided_at := null;
  new.void_reason := null;
  return new;  -- no balance, version, epoch, effect or cause change (contract invariant)
end;
$$;
revoke all on function mortgage_history_insert_locked() from public, anon, authenticated;
create trigger mortgage_history_payments_insert_locked before insert on mortgage_history_payments
  for each row execute function mortgage_history_insert_locked();
create trigger mortgage_history_escrow_insert_locked before insert on mortgage_history_escrow
  for each row execute function mortgage_history_insert_locked();

-- ---------------------------------------------------------------------------------------------------------------
-- 5. History voids and immutability (contract rules 3–4): only voided / voided_at / void_reason may change, once,
--    from active to voided; no loan lock and no balance effect, whatever the loan's state now.
-- ---------------------------------------------------------------------------------------------------------------
create or replace function mortgage_history_guard()
returns trigger
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if (to_jsonb(new) - array['voided', 'voided_at', 'void_reason']) is distinct from (to_jsonb(old) - array['voided', 'voided_at', 'void_reason']) then
    raise exception 'A recorded history entry can''t be changed. Void it and record a new entry instead.' using errcode = 'ZM5M2';
  end if;
  if old.voided then
    if not new.voided then
      raise exception 'A voided history entry can''t be restored. Record a new entry instead.' using errcode = 'ZM5M2';
    end if;
    new.voided_at := old.voided_at;
    new.void_reason := old.void_reason;
    return new;
  end if;
  if not new.voided then
    if (new.voided_at, new.void_reason) is distinct from (old.voided_at, old.void_reason) then
      raise exception 'Void details can only be set by voiding the entry.' using errcode = 'ZM5M2';
    end if;
    return new;
  end if;
  new.voided_at := coalesce(new.voided_at, now());
  return new;
end;
$$;
revoke all on function mortgage_history_guard() from public, anon, authenticated;
create trigger mortgage_history_payments_guard before update on mortgage_history_payments
  for each row execute function mortgage_history_guard();
create trigger mortgage_history_escrow_guard before update on mortgage_history_escrow
  for each row execute function mortgage_history_guard();
create trigger mortgage_history_payments_no_delete before delete on mortgage_history_payments
  for each row execute function mortgage_activity_no_delete();
create trigger mortgage_history_escrow_no_delete before delete on mortgage_history_escrow
  for each row execute function mortgage_activity_no_delete();

-- ---------------------------------------------------------------------------------------------------------------
-- 6. Audit (T3 condition 4): the table-name allowlist is extended ADDITIVELY from whatever the live constraint allows
--    (every existing name kept, including the integrity tables); both history tables join the generic audit trail.
-- ---------------------------------------------------------------------------------------------------------------
do $$
declare
  existing text[];
  def text;
begin
  select pg_get_constraintdef(oid) into def from pg_constraint
   where conrelid = 'public.audit_log'::regclass and conname = 'audit_log_table_name_check';
  -- The constraint can be in either form: ARRAY['a'::text, ...] (older migrations) or '{a,b,...}'::text[] (as written
  -- by 20261004100000). Read both; never continue with an empty list (that would drop every existing name).
  if def ~ '''\{' then
    existing := array(select btrim(x, ' "') from unnest(string_to_array(substring(def from '''\{([^}]*)\}'''), ',')) as x);
  else
    select array_agg(distinct m[1]) into existing from regexp_matches(coalesce(def, ''), '''([a-z_]+)''', 'g') as m;
  end if;
  if def is not null and coalesce(array_length(existing, 1), 0) = 0 then
    raise exception 'audit_log_table_name_check could not be read; refusing to rewrite it: %', def;
  end if;
  if def is not null and not (existing @> array['mortgage_details', 'mortgage_payments', 'mortgage_escrow_transactions']) then
    raise exception 'audit_log_table_name_check is missing expected names; refusing to rewrite it: %', def;
  end if;
  existing := array(select distinct x from unnest(coalesce(existing, '{}') || array['mortgage_history_payments', 'mortgage_history_escrow']) as x order by 1);
  if def is not null then
    execute 'alter table public.audit_log drop constraint audit_log_table_name_check';
  end if;
  execute format('alter table public.audit_log add constraint audit_log_table_name_check check (table_name = any (%L::text[]))', existing);
end;
$$;
create trigger mortgage_history_payments_audit_log
  after insert or update on mortgage_history_payments
  for each row execute function log_audit_changes();
create trigger mortgage_history_escrow_audit_log
  after insert or update on mortgage_history_escrow
  for each row execute function log_audit_changes();
